### ISSUE TITLE
Ajouter le temps de réponse dans les cartes de la page monitoring

### ISSUE THREAD

**Issue by ghoullier** [zetapush-demo/zetapush-projects-overview#1]
Cette info pourrait donner une idée relative tu temps de réponse de la platforme requetée.
<img width="453" alt="capture d ecran 2018-10-25 a 11 50 46" src="https://user-images.githubusercontent.com/2315749/47491964-3ef29700-d84c-11e8-8759-1e6734e686c5.png">

**Comment by pacome35220** [comment]
Bonne idée, je viens de le rajouter. Merci !
